# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [6]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [7]:
citydf=pd.read_csv("../WeatherPy/Weatherdf.csv")
citydf

,Unnamed: 0,City,Country,Temperature,Humidity,Cloudiness,Date,Wind Speed,Lat,Lng
0,0,Provideniya,RU,3.00,74,40,1603395197,8.00,64.38,-173.30
1,1,Boende,CD,22.72,95,100,1603395456,0.23,-0.22,20.87
2,2,Rikitea,PF,23.47,78,100,1603395171,6.41,-23.12,-134.97
3,3,Bluff,NZ,12.22,79,100,1603395456,2.24,-46.60,168.33
4,4,Jamestown,US,21.00,77,75,1603395284,2.60,42.10,-79.24
...,...,...,...,...,...,...,...,...,...,...
542,542,Petropavlovsk-Kamchatskiy,RU,-3.00,86,46,1603395588,3.00,53.05,158.65
543,543,Ust-Tsilma,RU,-5.93,96,0,1603395588,1.62,65.44,52.15
544,544,Verkhnyaya Inta,RU,-3.84,98,100,1603395454,5.03,65.98,60.31
545,545,Makīnsk,KZ,-2.52,93,84,1603395589,4.78,52.63,70.42
546,546,Bograd,RU,9.00,57,0,1603395589,4.00,54.23,90.83

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [10]:
# Configuring gmaps
gmaps.configure(api_key=g_key)

# Using Lat and Lng as locations and humidity as the weight.
locations = citydf[["Lat", "Lng"]]
humidity = citydf["Humidity"]

fig = gmaps.figure()
heatlayer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False)
heatlayer.max_intensity = 100
heatlayer.point_radius = 3

fig.add_layer(heatlayer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [13]:
idealweatherdf = citydf[(citydf['Temperature'] >= 20) & (citydf['Temperature'] <= 30)]
idealweatherdf = idealweatherdf[idealweatherdf['Wind Speed'] <= 5]
idealweatherdf = idealweatherdf[idealweatherdf['Cloudiness'] <= 10]
hotel_df = idealweatherdf
hotel_df

,Unnamed: 0,City,Country,Temperature,Humidity,Cloudiness,Date,Wind Speed,Lat,Lng
19,19,Buraidah,SA,23.00,25,0,1603395205,4.10,26.33,43.98
26,26,East London,ZA,20.00,88,0,1603395461,3.60,-33.02,27.91
49,49,Cuamba,MZ,23.76,45,0,1603395467,2.91,-14.80,36.54
58,58,Menongue,AO,22.24,46,2,1603395469,3.09,-14.66,17.69
64,64,Castro,BR,23.08,58,10,1603395440,4.44,-24.79,-50.01
75,75,Saint George,US,21.00,16,1,1603395323,3.15,37.10,-113.58
90,90,Faanui,PF,26.07,76,6,1603395476,4.78,-16.48,-151.75
98,98,Mahon,ES,21.00,83,0,1603395478,3.10,39.89,4.27
104,104,Lorengau,PG,27.25,75,3,1603395479,3.59,-2.02,147.27
111,111,Umluj,SA,28.37,43,0,1603395481,3.76,25.02,37.27
112,112,Ofakim,IL,23.33,67,0,1603395481,3.10,31.31,34.62
116,116,Cap Malheureux,MU,21.67,78,0,1603395482,1.34,-19.98,57.61
119,119,San Martín,AR,25.00,38,0,1603395483,3.10,-33.08,-68.47
128,128,Takoradze,GH,25.56,88,1,1603395485,4.00,4.88,-1.76
136,136,Goshāinganj,IN,24.31,58,4,1603395487,1.76,26.58,82.38
139,139,São Filipe,CV,27.46,72,0,1603395488,4.18,14.90,-24.50
169,169,Bilma,NE,28.90,14,0,1603395495,3.48,18.69,12.92
188,188,La Barca,MX,29.00,31,5,1603395499,1.32,20.28,-102.57
191,191,Mayo,US,25.56,88,1,1603395500,2.60,38.89,-76.51
225,225,Hualmay,PE,20.61,68,9,1603395484,4.72,-11.10,-77.61
228,228,Sawākin,SD,27.46,68,0,1603395508,2.60,19.11,37.33
237,237,Grand Gaube,MU,21.67,78,0,1603395510,1.34,-20.01,57.66
246,246,Wattegama,LK,26.00,100,0,1603395512,2.60,6.80,81.48
254,254,Najrān,SA,22.00,15,0,1603395514,1.00,17.49,44.13
271,271,Sabla,NG,28.43,17,0,1603395518,1.57,12.75,4.71
277,277,Tataouine,TN,25.00,31,0,1603395519,1.50,32.93,10.45
280,280,Half Moon Bay,US,24.44,31,5,1603395520,1.50,37.46,-122.43
282,282,Sur,OM,23.26,59,0,1603395468,2.42,22.57,59.53
288,288,Bud,US,25.56,61,0,1603395522,3.60,39.45,-86.18
298,298,Port Elizabeth,ZA,20.00,88,1,1603395464,4.60,-33.92,25.57
316,316,Lusaka,ZM,23.00,31,0,1603395530,2.60,-15.41,28.29
341,341,Hambantota,LK,26.00,100,0,1603395400,2.60,6.12,81.12
353,353,Amahai,ID,25.41,84,4,1603395539,1.23,-3.33,128.92
361,361,Kaduna,NG,24.92,27,5,1603395350,2.75,10.52,7.44
363,363,Sharjah city,AE,29.00,65,0,1603395348,1.50,25.36,55.40
379,379,Buin,CL,28.33,26,0,1603395366,4.10,-33.73,-70.75
410,410,Virden,US,27.78,63,0,1603395554,3.13,39.50,-89.77
422,422,Kita,ML,27.57,33,0,1603395557,0.49,13.03,-9.49
423,423,Banyuwangi,ID,23.99,87,10,1603395557,0.90,-8.23,114.36
447,447,Kahului,US,29.00,51,1,1603395563,2.10,20.89,-156.47
448,448,Noumea,NC,22.00,78,0,1603394947,1.00,-22.28,166.46
456,456,Salalah,OM,27.00,65,0,1603395483,1.50,17.02,54.09
457,457,Gaza,PS,25.00,61,0,1603395567,2.10,31.50,34.47
484,484,Westport,US,22.22,73,1,1603395574,2.60,41.14,-73.36
489,489,Pasuruan,ID,25.89,78,6,1603395575,1.22,-7.65,112.91
508,508,Iranshahr,IR,21.00,6,0,1603395580,4.10,27.20,60.68
517,517,General Roca,AR,20.00,52,0,1603395582,2.60,-39.03,-67.58
531,531,Albertville,US,25.56,71,0,1603395585,0.89,34.27,-86.21
537,537,Māngrol,IN,27.70,66,1,1603395587,4.65,21.12,70.12

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [19]:
#adding the new column to the DF
hotel_df["Hotel Name"] = ""

for index, row in hotel_df.iterrows():
    try:
        
        baseurl = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

        params = {
        "keyword": "hotel",
        "radius": 5000,
        "key": g_key,
        }


        lat = row['Lat']
        lng = row['Lng']

        params['location'] = f"{lat}, {lng}"

        hoteldata = requests.get(baseurl, params=params).json()
        
        hotel_df.loc[index, "Hotel Name"] = hoteldata["results"][0]["name"]
        
    except IndexError:
        
        hotel_df.loc[index, "Hotel Name"] = "NaN"
        
hotel_df

,Unnamed: 0,City,Country,Temperature,Humidity,Cloudiness,Date,Wind Speed,Lat,Lng,Hotel Name
19,19,Buraidah,SA,23.00,25,0,1603395205,4.10,26.33,43.98,فندق تاورز HOTELTOWERS
26,26,East London,ZA,20.00,88,0,1603395461,3.60,-33.02,27.91,Premier Hotels & Resorts
49,49,Cuamba,MZ,23.76,45,0,1603395467,2.91,-14.80,36.54,Daania Residence
58,58,Menongue,AO,22.24,46,2,1603395469,3.09,-14.66,17.69,Ritz Lauca
64,64,Castro,BR,23.08,58,10,1603395440,4.44,-24.79,-50.01,Urano Business Hotel
75,75,Saint George,US,21.00,16,1,1603395323,3.15,37.10,-113.58,"The Advenire, Autograph Collection"
90,90,Faanui,PF,26.07,76,6,1603395476,4.78,-16.48,-151.75,InterContinental Bora Bora Resort Thalasso Spa
98,98,Mahon,ES,21.00,83,0,1603395478,3.10,39.89,4.27,Síndic Hotel
104,104,Lorengau,PG,27.25,75,3,1603395479,3.59,-2.02,147.27,Lorengau Harbourside Hotel
111,111,Umluj,SA,28.37,43,0,1603395481,3.76,25.02,37.27,Shada Collection Mina Hotel
112,112,Ofakim,IL,23.33,67,0,1603395481,3.10,31.31,34.62,NaN
116,116,Cap Malheureux,MU,21.67,78,0,1603395482,1.34,-19.98,57.61,LUX Grand Gaube Resort & Villas
119,119,San Martín,AR,25.00,38,0,1603395483,3.10,-33.08,-68.47,Delacava Hotel Boutique
128,128,Takoradze,GH,25.56,88,1,1603395485,4.00,4.88,-1.76,Protea Hotel by Marriott Takoradi Select
136,136,Goshāinganj,IN,24.31,58,4,1603395487,1.76,26.58,82.38,NaN
139,139,São Filipe,CV,27.46,72,0,1603395488,4.18,14.90,-24.50,Hotel Savana
169,169,Bilma,NE,28.90,14,0,1603395495,3.48,18.69,12.92,NaN
188,188,La Barca,MX,29.00,31,5,1603395499,1.32,20.28,-102.57,Hotel Fina Inn
191,191,Mayo,US,25.56,88,1,1603395500,2.60,38.89,-76.51,NaN
225,225,Hualmay,PE,20.61,68,9,1603395484,4.72,-11.10,-77.61,Hotel Terrazas Del Mar - Huacho
228,228,Sawākin,SD,27.46,68,0,1603395508,2.60,19.11,37.33,Arab Plaza Hotel عرب بلازا هوتيل
237,237,Grand Gaube,MU,21.67,78,0,1603395510,1.34,-20.01,57.66,LUX Grand Gaube Resort & Villas
246,246,Wattegama,LK,26.00,100,0,1603395512,2.60,6.80,81.48,NaN
254,254,Najrān,SA,22.00,15,0,1603395514,1.00,17.49,44.13,NaN
271,271,Sabla,NG,28.43,17,0,1603395518,1.57,12.75,4.71,NaN
277,277,Tataouine,TN,25.00,31,0,1603395519,1.50,32.93,10.45,Sangho Privilege Tataouine
280,280,Half Moon Bay,US,24.44,31,5,1603395520,1.50,37.46,-122.43,"The Ritz-Carlton, Half Moon Bay"
282,282,Sur,OM,23.26,59,0,1603395468,2.42,22.57,59.53,Sur Plaza Hotel
288,288,Bud,US,25.56,61,0,1603395522,3.60,39.45,-86.18,NaN
298,298,Port Elizabeth,ZA,20.00,88,1,1603395464,4.60,-33.92,25.57,Island Way Villa
316,316,Lusaka,ZM,23.00,31,0,1603395530,2.60,-15.41,28.29,"Radisson Blu Hotel, Lusaka"
341,341,Hambantota,LK,26.00,100,0,1603395400,2.60,6.12,81.12,The Peacock Beach Hotel Hambantota
353,353,Amahai,ID,25.41,84,4,1603395539,1.23,-3.33,128.92,HOTEL ISABELA
361,361,Kaduna,NG,24.92,27,5,1603395350,2.75,10.52,7.44,castle de white house hotel kaduna
363,363,Sharjah city,AE,29.00,65,0,1603395348,1.50,25.36,55.40,"The Chedi Al Bait, Sharjah - a GHM hotel"
379,379,Buin,CL,28.33,26,0,1603395366,4.10,-33.73,-70.75,Paihuen
410,410,Virden,US,27.78,63,0,1603395554,3.13,39.50,-89.77,NaN
422,422,Kita,ML,27.57,33,0,1603395557,0.49,13.03,-9.49,HÔTEL LE RELAIS
423,423,Banyuwangi,ID,23.99,87,10,1603395557,0.90,-8.23,114.36,Aston Banyuwangi Hotel & Conference Center
447,447,Kahului,US,29.00,51,1,1603395563,2.10,20.89,-156.47,Maui Beach Hotel
448,448,Noumea,NC,22.00,78,0,1603394947,1.00,-22.28,166.46,Nouvata
456,456,Salalah,OM,27.00,65,0,1603395483,1.50,17.02,54.09,Alpha Suites Hotel
457,457,Gaza,PS,25.00,61,0,1603395567,2.10,31.50,34.47,فندق جراند بالاس Grand Palace Hotel
484,484,Westport,US,22.22,73,1,1603395574,2.60,41.14,-73.36,Hilton Garden Inn Norwalk
489,489,Pasuruan,ID,25.89,78,6,1603395575,1.22,-7.65,112.91,Hotel Horison Pasuruan
508,508,Iranshahr,IR,21.00,6,0,1603395580,4.10,27.20,60.68,هتل قصر
517,517,General Roca,AR,20.00,52,0,1603395582,2.60,-39.03,-67.58,Hotel Huemul
531,531,Albertville,US,25.56,71,0,1603395585,0.89,34.27,-86.21,Microtel Inn & Suites by Wyndham Albertville
537,537,Māngrol,IN,27.70,66,1,1603395587,4.65,21.12,70.12,NaN

In [20]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [21]:

# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
fig

# Display Map

Figure(layout=FigureLayout(height='420px'))